# Full classification of every unique photo, by index in photo_order.txt.
# cat, label.  cat "x" = deliberately held back.
PHOTOS = {
1:("local","Front Street, a few minutes down the coast"),
2:("view","Sailboats crossing the channel"),
3:("view","Afternoon sails off the point"),
4:("view","Open water from the lanai"),
5:("bedroom","The bed, with the Aloha sign"),
6:("sunset","A palm against the last light"),
7:("kitchen","Full kitchen, looking in"),
8:("kitchen","The breakfast bar"),
9:("view","Outrigger canoes going by"),
10:("view","Paddlers on a flat morning"),
11:("sunset","A sail crossing the sun"),
12:("lanai","Cushioned chairs at the near end"),
13:("lanai","The lanai runs the full length of the unit"),
14:("view","Palms, water, and the island beyond"),
15:("beach","The beach below the building"),
16:("kitchen","Kitchen and breakfast bar"),
17:("lanai","Seating among the planters"),
18:("view","The island across the channel"),
19:("bedroom","Bedroom, morning light"),
20:("lanai","Looking out through the palms"),
21:("x","owners"),
22:("beach","Where the lawn meets the sand"),
23:("living","The living room opens onto the lanai"),
24:("beach","Reef and palms"),
25:("view","The channel, wide open"),
26:("beach","Low water over the reef"),
27:("living","Inside, looking out"),
28:("bedroom","Aloha"),
29:("sunset","The sun going down"),
30:("sunset","Cloud and fire"),
31:("x","owners"),
32:("local","Shops along the coast road"),
33:("sunset","Evening over the water"),
34:("sunset","Palm and last light"),
35:("moon","Moonlight on the water"),
36:("view","A fleet of sails"),
37:("living","The living room"),
38:("beach","Palms over the reef"),
39:("honu","A honu hauled out on the sand"),
40:("honu","Close enough, and no closer"),
41:("rainbow","A rainbow over the channel"),
42:("sunset","Sunset caught on the wet sand"),
43:("rainbow","Rain passing along the shore"),
44:("beach","The beach, looking down the coast"),
45:("x","guests"),46:("x","guest"),
47:("view","Reef, then the island"),
48:("lanai","Looking down over the grounds"),
49:("x","children"),50:("x","children"),
51:("x","guests"),52:("x","guests"),53:("x","guests"),
54:("beach","Palms along the sand"),
55:("view","The island on a clear day"),
56:("beach","A palm leaning over the beach"),
57:("view","Water to the horizon"),
58:("x","guests"),
59:("view","A flat, still morning"),
60:("beach","The shoreline at noon"),
61:("x","guest"),62:("x","guests"),
63:("beach","Reef shelf at low tide"),
64:("rainbow","A rainbow through the palms"),
65:("view","The whole channel at once"),
66:("beach","Palms and open sand"),
67:("sunset","The sun breaking through the palms"),
68:("beach","Surf on the reef"),
69:("beach","A palm over the water"),
70:("sunset","Cloud lit from underneath"),
71:("sunset","Figures on the sand at dusk"),
72:("living","Rattan seating and the sea beyond"),
73:("living","Living room, looking to the lanai"),
74:("lanai","Loungers at the far end"),
75:("living","The sitting area"),
76:("moon","A sailboat on a moonlit sea"),
77:("entry","The entry"),
78:("entry","The hallway, with the fern"),
79:("lanai","Chairs facing the water"),
80:("living","Living room and the lanai door"),
81:("lanai","Binoculars kept on the rail"),
82:("x","guest"),
83:("entry","Entry, looking through"),
84:("entry","The console table"),
85:("entry","Entry and the light from the lanai"),
86:("entry","Down the hall"),
87:("kitchen","Kitchen, the working end"),
88:("x","owners"),
89:("entry","The fern by the door"),
90:("sunset","A sail on the sunset"),
91:("lanai","The deck below"),
92:("moon","The moon laying a path on the water"),
93:("entry","Entry through to the living room"),
94:("view","Palm and weather"),
95:("entry","Hall, living room, lanai"),
96:("bathroom","The bathroom"),
97:("lanai","Rail, planters, open water"),
98:("moon","Moon behind a palm"),
99:("lanai","Rocking chairs on the lanai"),
100:("lanai","Cushions and palms"),
101:("lanai","Privacy, please"),
102:("building","The building from the grounds"),
103:("living","Living room and the view"),
104:("lanai","Set up to watch the water"),
105:("lanai","Planters the length of the rail"),
106:("building","O thank Heaven 4 — 711"),
107:("kitchen","Kitchen, full length"),
108:("kitchen","Fruit on the counter"),
109:("beach","The deck down to the sand"),
110:("kitchen","A lei on the counter"),
111:("building","Maui Sands Seaside"),
112:("kitchen","Kitchen, from the bar"),
113:("bathroom","Bathroom, looking in"),
114:("sunset","Dusk, framed"),
115:("lanai","Cactus on the lanai"),
116:("lanai","Director's chairs by the door"),
117:("x","owners"),
118:("kitchen","Kitchen and breakfast stools"),
119:("living","The room, end to end"),
120:("living","Living room toward the lanai"),
121:("view","Palm over turquoise"),
122:("kitchen","The kitchen, wide"),
123:("beach","A cairn on the rocks"),
124:("x","guest"),
125:("honu","A gecko on the window"),
126:("rainbow","A rainbow standing over the palms"),
127:("beach","Lawn, palms, and the sand"),
128:("sunset","Two palms and the setting sun"),
129:("x","guests on the lawn"),
130:("sunset","Sunset from the beach"),
131:("x","guests"),
132:("beach","The shore in the afternoon"),
133:("x","guests"),
134:("sunset","The sand going gold"),
135:("moon","Moonrise through the palm"),
136:("moon","Moonlight between the palms"),
137:("building","The building from the beach"),
138:("x","AI mockup - never publish as a photo of the property"),
}

# Video clips, by representative filename.
VIDEOS = {
"074":("lanai","Looking out through the palms"),
"051":("lanai","The view from the rail"),
"110":("lanai","Walking the length of the lanai"),
"210":("beach","Reef water, close up"),
"063":("beach","The shore below"),
"087":("beach","Surf on a grey morning"),
"125":("beach","Palms over the reef"),
"179":("building","The grounds and the sand"),
"129_711 Rainbow video":("rainbow","A rainbow over the water"),
"198":("sunset","The sun going into the channel"),
"192":("sunset","Orange cloud at the end of the day"),
"170":("sunset","A sail against the sunset"),
"161":("sunset","The beach at golden hour"),
"149":("moon","Moonlight on a dark sea"),
"207":("building","O thank Heaven 4 — 711"),
}

CATS = [
 ("lanai",    "The Lanai",            "Thirty-five feet of it, the length of the unit."),
 ("living",   "Living Room",          "Opens onto the lanai, so the two read as one room."),
 ("bedroom",  "Bedroom",              "One bedroom, and the Aloha sign over the bed."),
 ("kitchen",  "Kitchen",              "Full kitchen with a breakfast bar."),
 ("bathroom", "Bathroom",             "Updated, with a walk-in shower."),
 ("entry",    "Entry & Hallway",      "The way in, and the light that comes down it."),
 ("view",     "The View",             "180 degrees of open water and the island across the channel."),
 ("sunset",   "Sunsets",              "Seven years of them, from the same rail."),
 ("rainbow",  "Rainbows",             "Rain here lasts four minutes and leaves one behind."),
 ("moon",     "Moonlight",            "What the lanai does after dark."),
 ("beach",    "The Beach & Reef",     "It starts where the lawn ends."),
 ("honu",     "Honu & Wildlife",      "Green sea turtles haul out below the building."),
 ("building", "The Building",         "Maui Sands Seaside, and the door to 711."),
 ("local",    "Nearby",               "The coast road and what is on it."),
]
